[package]
name = "warp-users-proxy"
version = "0.1.0"
authors = ["Nicholas Young <nicholas@nicholaswyoung.com>"]
edition = "2018"
license = "MPL-2.0"
readme = "README.md"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.22"
color-eyre = "0.5.7"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
validator = { version = "0.11.0", features = ["derive"] }
reqwest = { version = "0.10.8", features = ["json"] }
warp = "0.2.5"
tokio = { version = "0.2.22", features = ["rt-threaded", "macros"] }
tracing = "0.1.21"
listenfd = "0.3.3"
hyper = "0.13.9"

[[bin]]
name = "warp-users-proxy"
path = "src/main.rs"
